logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  #  session:
  #    redis:
  #      flush-mode: on_save
  #      namespace: spring:session
  data:
    redis:
      host: localhost
      password: 1234
      port: 6379
      refresh-token:
        host: localhost
        port: 6379

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deepdive?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#  server:
#    servlet:
#      session:
#        timeout: 3600
#  port: 8080
