logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
  data:
    redis:
      host: localhost
      password: 1234
      port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/deepdive
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    session:
      timeout: 3600